"""
Pydantic output schemas for structured output enforcement (BP-STRUCT-04).

Defines validated output models for critical LLM-facing components:
- RouterOutput: Route classifier JSON response
- PlannerComponentOutput: ToT planner graph components
- ValueOutput: ToT value evaluation scores
"""

from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field, field_validator


class RouterOutput(BaseModel):
    """Validated output schema for the route classifier.

    Normalises and constrains LLM routing responses so that
    downstream code always receives clean, typed data.
    """

    route: str
    confidence: Optional[float] = None
    reasoning: str = ""

    model_config = {"extra": "ignore"}

    @field_validator("route", mode="before")
    @classmethod
    def normalize_route(cls, v: Any) -> str:
        return str(v).strip().lower()

    @field_validator("confidence", mode="before")
    @classmethod
    def clamp_confidence(cls, v: Any) -> Optional[float]:
        if v is None:
            return None
        return max(0.0, min(1.0, float(v)))


class PlannerComponentOutput(BaseModel):
    """Validated output schema for individual ToT planner components.

    Covers all three component types generated by the Tree-of-Thought
    planner: nodes, edges, and parallel groups.  Fields that do not
    apply to the current ``component_type`` are left as ``None``.
    """

    component_type: Literal["node", "edge", "parallel_group"]

    # Node fields
    name: Optional[str] = None
    type: Optional[str] = None
    agent: Optional[str] = None
    objective: Optional[str] = None
    expected_output: Optional[str] = None
    tools: Optional[List[str]] = None

    # Edge fields
    source: Optional[str] = None
    target: Optional[str] = None
    from_node: Optional[str] = None
    to_node: Optional[str] = None
    condition: Optional[str] = None

    # Parallel group fields
    nodes: Optional[List[str]] = None
    parallel_nodes: Optional[List[Dict[str, Any]]] = None

    model_config = {"extra": "ignore"}


class ValueOutput(BaseModel):
    """Validated output schema for ToT value evaluation.

    Ensures the ``score`` is always a float in [0, 10].
    """

    score: float = Field(ge=0, le=10)
    reason: str = ""

    model_config = {"extra": "ignore"}

    @field_validator("score", mode="before")
    @classmethod
    def coerce_score(cls, v: Any) -> float:
        return max(0.0, min(10.0, float(v)))
