"""
Test suite for ToT Graph Planner orphaned nodes fixes.

Tests the comprehensive fixes implemented to prevent and resolve orphaned nodes
in graph specifications generated by ToT LLM.
"""

import pytest
import logging
from orchestrator.planning.tot_graph_planner import (
    _validate_parallel_group_references,
    _find_closest_node_name,
    _create_nodes_from_parallel_group,
    _auto_fix_graph,
)
from orchestrator.planning.graph_specifications import (
    StateGraphSpec,
    GraphNodeSpec,
    NodeType,
    ParallelGroup,
)
from orchestrator.core.config import AgentConfig

# Configure logging for tests
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class TestFuzzyNodeMatching:
    """Test fuzzy matching functionality for auto-correcting node references."""

    def test_exact_match(self):
        """Test exact name matching."""
        available = {"research", "analysis", "quality_assurance"}
        result = _find_closest_node_name("research", available)
        assert result == "research"

    def test_suffix_removal_task(self):
        """Test suffix removal: 'research_task' -> 'research'."""
        available = {"research", "analysis", "quality_assurance"}
        result = _find_closest_node_name("research_task", available)
        assert result == "research"

    def test_suffix_removal_node(self):
        """Test suffix removal: 'analysis_node' -> 'analysis'."""
        available = {"research", "analysis", "quality_assurance"}
        result = _find_closest_node_name("analysis_node", available)
        assert result == "analysis"

    def test_substring_matching(self):
        """Test substring matching: 'quality' -> 'quality_assurance'."""
        available = {"research", "analysis", "quality_assurance"}
        result = _find_closest_node_name("quality", available)
        assert result == "quality_assurance"

    def test_no_match_found(self):
        """Test behavior when no close match exists."""
        available = {"research", "analysis"}
        result = _find_closest_node_name("completely_different", available)
        assert result is None

    def test_case_insensitive_matching(self):
        """Test case-insensitive matching."""
        available = {"Research", "Analysis", "QualityAssurance"}
        result = _find_closest_node_name("research", available)
        assert result == "Research"


class TestParallelGroupValidation:
    """Test parallel group reference validation."""

    def test_valid_references(self):
        """Test validation with all valid references."""
        graph_spec = StateGraphSpec(name="test_graph")
        graph_spec.add_node(GraphNodeSpec(name="research", type=NodeType.AGENT, agent="Researcher"))
        graph_spec.add_node(GraphNodeSpec(name="analysis", type=NodeType.AGENT, agent="Analyst"))

        parallel_group = ParallelGroup(
            group_id="parallel_work",
            nodes=["research", "analysis"]
        )
        graph_spec.add_parallel_group(parallel_group)

        # Should not raise or modify
        _validate_parallel_group_references(graph_spec)
        assert parallel_group.nodes == ["research", "analysis"]

    def test_auto_correct_task_suffix(self):
        """Test auto-correction of _task suffix."""
        graph_spec = StateGraphSpec(name="test_graph")
        graph_spec.add_node(GraphNodeSpec(name="research", type=NodeType.AGENT, agent="Researcher"))
        graph_spec.add_node(GraphNodeSpec(name="analysis", type=NodeType.AGENT, agent="Analyst"))

        parallel_group = ParallelGroup(
            group_id="parallel_work",
            nodes=["research_task", "analysis_task"]  # Invalid references
        )
        graph_spec.add_parallel_group(parallel_group)

        # Should auto-correct
        _validate_parallel_group_references(graph_spec)
        assert parallel_group.nodes == ["research", "analysis"]

    def test_remove_invalid_reference(self):
        """Test removal of invalid references with no close match."""
        graph_spec = StateGraphSpec(name="test_graph")
        graph_spec.add_node(GraphNodeSpec(name="research", type=NodeType.AGENT, agent="Researcher"))

        parallel_group = ParallelGroup(
            group_id="parallel_work",
            nodes=["research", "nonexistent_node"]
        )
        graph_spec.add_parallel_group(parallel_group)

        # Should remove invalid reference
        _validate_parallel_group_references(graph_spec)
        assert parallel_group.nodes == ["research"]

    def test_mixed_valid_invalid_references(self):
        """Test validation with mix of valid, correctable, and invalid references."""
        graph_spec = StateGraphSpec(name="test_graph")
        graph_spec.add_node(GraphNodeSpec(name="research", type=NodeType.AGENT, agent="Researcher"))
        graph_spec.add_node(GraphNodeSpec(name="analysis", type=NodeType.AGENT, agent="Analyst"))

        parallel_group = ParallelGroup(
            group_id="parallel_work",
            nodes=["research", "analysis_task", "invalid_node"]
        )
        graph_spec.add_parallel_group(parallel_group)

        # Should keep valid, correct suffix, remove invalid
        _validate_parallel_group_references(graph_spec)
        assert set(parallel_group.nodes) == {"research", "analysis"}


class TestAutoNodeCreationDisabled:
    """Test that auto-node-creation is disabled and validates properly."""

    def test_no_node_creation(self):
        """Test that nodes are NOT auto-created."""
        graph_spec = StateGraphSpec(name="test_graph")
        existing_nodes = []

        agent_catalog = [
            AgentConfig(name="Researcher", role="Research Specialist", goal="Gather information"),
            AgentConfig(name="Analyst", role="Data Analyst", goal="Analyze data"),
        ]

        # Call with non-existent node references
        _create_nodes_from_parallel_group(
            parallel_nodes=["research_task", "analysis_task"],
            agent_catalog=agent_catalog,
            existing_nodes=existing_nodes
        )

        # Should NOT create nodes
        assert len(existing_nodes) == 0

    def test_validation_only_mode(self):
        """Test that function only validates, doesn't modify."""
        existing_nodes = [
            GraphNodeSpec(name="research", type=NodeType.AGENT, agent="Researcher")
        ]
        agent_catalog = [
            AgentConfig(name="Researcher", role="Research Specialist", goal="Gather information")
        ]

        # Call with mix of existing and non-existing
        _create_nodes_from_parallel_group(
            parallel_nodes=["research", "nonexistent"],
            agent_catalog=agent_catalog,
            existing_nodes=existing_nodes
        )

        # Should not modify existing_nodes
        assert len(existing_nodes) == 1
        assert existing_nodes[0].name == "research"


class TestAutoFixGraph:
    """Test comprehensive auto-fix process."""

    def test_auto_fix_with_validation(self):
        """Test that auto-fix validates and reports success/failure."""
        graph_spec = StateGraphSpec(name="test_graph")

        # Add nodes
        graph_spec.add_node(GraphNodeSpec(name="start", type=NodeType.START))
        graph_spec.add_node(GraphNodeSpec(name="research", type=NodeType.AGENT, agent="Researcher"))
        graph_spec.add_node(GraphNodeSpec(name="end", type=NodeType.END))

        # Add parallel group with correctable reference
        parallel_group = ParallelGroup(
            group_id="parallel_work",
            nodes=["research_task"]  # Will be auto-corrected to "research"
        )
        graph_spec.add_parallel_group(parallel_group)

        # Run auto-fix
        _auto_fix_graph(graph_spec)

        # Verify parallel group was corrected
        assert graph_spec.parallel_groups[0].nodes == ["research"]

        # Verify edges were created
        assert len(graph_spec.edges) > 0

        # Verify validation passes
        errors = graph_spec.validate()
        assert not errors, f"Validation should pass after auto-fix, but got: {errors}"


class TestPromptExampleConsistency:
    """Test that prompt examples use consistent naming (no _task suffix)."""

    def test_prompt_examples_no_task_suffix(self):
        """Verify prompt examples don't use _task suffix."""
        from orchestrator.planning.tot_graph_planner import GraphPlanningTask
        from orchestrator.core.config import AgentConfig

        # Create minimal task
        agent_catalog = [
            AgentConfig(name="Researcher", role="Research Specialist", goal="Gather information")
        ]
        task = GraphPlanningTask(
            problem_statement="Test problem",
            agent_catalog=agent_catalog,
            max_steps=3,
            settings=None
        )

        # Get prompt
        prompt = task._base_graph_prompt("Test problem")

        # Verify examples don't contain "_task" suffix
        assert "research_task" not in prompt, "Prompt should not contain 'research_task'"
        assert "analysis_task" not in prompt, "Prompt should not contain 'analysis_task'"

        # Verify correct examples are present
        assert '"name":"research"' in prompt or '"name": "research"' in prompt
        assert '"name":"analysis"' in prompt or '"name": "analysis"' in prompt


if __name__ == "__main__":
    # Run tests
    pytest.main([__file__, "-v", "--tb=short"])
