---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	start(start)
	research_f1_teams(research_f1_teams)
	research_f1_drivers(research_f1_drivers)
	analyze_results(analyze_results)
	quality_assurance(quality_assurance)
	final_report(final_report)
	end(end)
	__end__([<p>__end__</p>]):::last
	__start__ --> start;
	analyze_results --> quality_assurance;
	final_report --> end;
	quality_assurance --> final_report;
	research_f1_drivers --> end;
	research_f1_teams --> end;
	start --> analyze_results;
	start --> research_f1_drivers;
	start --> research_f1_teams;
	end --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
